sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.8
  - DJANGO_VERSION=2.0

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install 'django-jsonfield >= 1.0.1, < 2.0.0a0' coverage

script: coverage run --source=. ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.0
  include:
    - python: 3.6
      env: DJANGO_VERSION=1.11.8
    - python: 3.6
      env: DJANGO_VERSION=2.0
