language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5.1
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install django-jsonfield

script: python setup.py test

matrix:
  exclude:
    - python: 3.2
      env: DJANGO_VERSION=1.4.3
    - python: 3.3
      env: DJANGO_VERSION=1.4.3
    - python: 3.4
      env: DJANGO_VERSION=1.4.3
