dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO_VERSION=1.11.20
  - DJANGO_VERSION=2.0.13
  - DJANGO_VERSION=2.1.8
  - DJANGO_VERSION=2.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install 'django-jsonfield >= 1.1.0, < 2.0.0a0' coverage

script: coverage run --source=. ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - python: 2.7
      env: DJANGO_VERSION=1.11.20
    - python: 3.4
      env: DJANGO_VERSION=1.11.20
    - python: 3.4
      env: DJANGO_VERSION=2.0.13
