dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=2.2.8
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install 'django-jsonfield >= 1.1.0, < 2.0.0a0' coverage

script: coverage run --source=. ./runtests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: checks & publish
      before_install: pip install poetry
      install: poetry install
      script: poetry run inv check.all
      deploy:
        provider: script
        script: poetry publish --build
        on:
          tags: true
