language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5.1
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install django-jsonfield coverage python-coveralls

script: coverage run --source=. ./setup.py test

after_success:
  - coveralls

matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.3
    - python: 3.4
      env: DJANGO_VERSION=1.4.3
    - python: 3.5
      env: DJANGO_VERSION=1.4.3
