sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.14
  - DJANGO_VERSION=1.9.9

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-jsonfield coverage

script: coverage run --source=. ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.9.9
  include:
    - python: 3.5
      env: DJANGO_VERSION=1.8.14
    - python: 3.5
      env: DJANGO_VERSION=1.9.9
